apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8ssandra-docker
spec:
  selector:
    matchLabels:
      app: k8ssandra-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: k8ssandra-docker
        env: gcp
    spec:
      containers:
      - name: k8ssandra-docker
        image: docker.io/dsstevenmatison/k8ssandra-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: KEYSPACE
            value: "demo"
          - name: K8S_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8ssandra-superuser 
                key: username
          - name: K8S_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: k8ssandra-superuser 
                key: password               
          - name: K8S_AUTH_URL
            value: "http://k8ssandra-dc1-stargate-service:8081/v1/auth"
          - name: STARGATE_URL
            value: "http://k8ssandra-dc1-stargate-service:8082"
          - name: GRAPHQL_URL
            value: "http://k8ssandra-dc1-stargate-service:8080/graphql/"